insert into company (name) values 
('General'),
('Zscaler'),
('Nuclei'),
('Avalara'),
('Carwale'),
('Dice'),
('Quantiphi'),
('Unthinkable Solutions'),
('Safesend'),
('Infosys'),
('Accenture'),
('Nuceus Tech'),
('Cognizant'),
('LTTS'),
('LTI Mindtree'),
('ConsultAdd'),
('IDFC Fisrt Bank'),
('Barclays'),
('MasterCard'),
('Beghou'),
('Lumber'),
('Shakti Pump'),
('Volvo Eicher'),
('LG'),
('Deutche Bank');